### ISSUE TITLE
How to solve？There is a problem using diffusers pipeline 

### ISSUE THREAD

**Issue by klossm** [seruva19/kubin#101]
name 'KandinskyPriorPipeline' is not defined

Traceback (most recent call last):
  File "M:\ai\kubin\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "M:\ai\kubin\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "M:\ai\kubin\venv\lib\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "M:\ai\kubin\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "M:\ai\kubin\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "M:\ai\kubin\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "M:\ai\kubin\src\ui_blocks\t2i.py", line 105, in generate
    return generate_fn(params)
  File "M:\ai\kubin\src\webui.py", line 32, in <lambda>
    generate_fn=lambda params: kubin.model.t2i(params),
  File "M:\ai\kubin\src\models\model_diffusers.py", line 214, in t2i
    params = self.prepare("text2img").seed(params)
  File "M:\ai\kubin\src\models\model_diffusers.py", line 56, in prepare
    self.pipe_prior = KandinskyPriorPipeline.from_pretrained(
NameError: name 'KandinskyPriorPipeline' is not defined

**Comment by seruva19** [comment]
Try installing diffusers manually:

```
call venv\Scripts\activate.bat
pip install -r diffusers/requirements.txt
```

(from command line)

**Comment by klossm** [comment]
> Try installing diffusers manually:
> 
> ```
> call venv\Scripts\activate.bat
> pip install -r diffusers/requirements.txt
> ```
> 
> (from command line)

I have already installed this, but I still reported an error.

**Comment by seruva19** [comment]
1. Do you launch app with `start.bat` ?

2. Try type this, is the error raised?

```
call venv\Scripts\activate.bat
python -c "from diffusers import KandinskyPriorPipeline"
```

**Comment by seruva19** [comment]
absl?? That's so weird...
Try installing  it manually:

```
call venv\Scripts\activate.bat
pip install absl-py
```

**Comment by klossm** [comment]
> 

I followed the error prompt to add the following.
Pip install absl-py.
Pip install wrapt.
Pip install opt_einsum.
Pip install gast.
Pip install astunparse.
Pip install flatbuffers.

Then run start.bat.


The corresponding model is being downloaded now. It should be running successfully.
