### ISSUE TITLE
2.1 UnClip finetune error when enable Inpainting option

### ISSUE THREAD

**Issue by brucelil** [seruva19/kubin#145]
logs:
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
finetuning unclip model, epoch 1/100:   0%|                                                                                                          | 0/1086 [02:03<?, ?it/s]
finetuning unclip model, epoch 1/100:   0%|                                                                                                          | 0/1086 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/home/ubuntu/data/kubin-dev/kubin/extensions/kd-training/train_modules/train_21/train_unclip_ui.py", line 617, in launch_training
    start_unclip_training(kubin, training_config)
  File "/home/ubuntu/data/kubin-dev/kubin/extensions/kd-training/train_modules/train_21/train_unclip.py", line 145, in start_unclip_training
    train_unclip(
  File "/home/ubuntu/data/kubin-dev/kubin/extensions/kd-training/train_modules/train_utils/trainer_2_1_uclip.py", line 99, in train_unclip
    losses = compute_losses()
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/kandinsky2/model/respace.py", line 107, in training_losses
    return super().training_losses(self._wrap_model(model), *args, **kwargs)
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/kandinsky2/model/gaussian_diffusion.py", line 702, in training_losses
    model_output = model(x_t, self._scale_timesteps(t), **model_kwargs)
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/kandinsky2/model/respace.py", line 133, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
**TypeError: Text2ImUNet.forward() got an unexpected keyword argument 'inpaint_image'**

**Comment by seruva19** [comment]
Fixed in latest commit.

**Comment by brucelil** [comment]
test again:
   response = f(*args, **kwargs)
  File "/home/ubuntu/data/kubin-dev/kubin/extensions/kd-training/train_modules/train_21/train_unclip_ui.py", line 617, in launch_training
    start_unclip_training(kubin, training_config)
  File "/home/ubuntu/data/kubin-dev/kubin/extensions/kd-training/train_modules/train_21/train_unclip.py", line 116, in start_unclip_training
    model.load_state_dict(torch.load(config["params_path"]))
  File "/home/ubuntu/data/kubin-dev/kubin/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for InpaintText2ImUNet:
        size mismatch for input_blocks.0.0.weight: copying a param with shape torch.Size([384, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 9, 3, 3]).
