### ISSUE TITLE
kd-animation error

### ISSUE THREAD

**Issue by videoprice** [seruva19/kubin#150]
hi, have a error in kd-animation "No module named 'deforum_kandinsky'"

**Comment by seruva19** [comment]
'deforum_kandinsky' is a folder from the root of original repo https://github.com/ai-forever/deforum-kandinsky and it is downloaded in runtime during installation of the 'kd-animation' extension. This error probably means that for whatever reasons the contents of the repo was not downloaded.
What you can try is to clone or download the 'kandinsky-deforum' repo and just put folder 'deforum_kandinsky' from there to 'extensions/kd-animation' folder inside kubin root directory. And it should work.

**Comment by videoprice** [comment]
ok, but now have a second error:
"error
Model_Diffusers22' object has no attribute 'prepare_model"

thanks

**Comment by seruva19** [comment]
Check the output of command `git log --pretty=format:'%h' -n 1` launched from the application root.
The result should be `'0425422'`.
If it's not, then for some reasons your application is outdated and you have to update it using `git pull` or update script.

**Comment by videoprice** [comment]
thanks, update is done, but same error is still here

Traceback (most recent call last):
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\video\AppData\Roaming\Python\Python310\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "W:\kubin\extensions/kd-animation/setup_ext.py", line 69, in <lambda>
    fn=lambda *params: create_deforum_animation(
  File "W:\kubin\extensions/kd-animation/setup_ext.py", line 117, in create_deforum_animation
    prior, decoder = kubin.model.prepare_model("img2img")
AttributeError: 'Model_Diffusers22' object has no attribute 'prepare_model'

**Comment by seruva19** [comment]
Can you try to do a fresh install (in some other folder)? I cannot understand the origin of this error.
