### ISSUE TITLE
After update, error

### ISSUE THREAD

**Issue by videoprice** [seruva19/kubin#50]
found 10 extensions
1: extension 'fb-styles' found
Traceback (most recent call last):
  File "W:\kubin\src\kubin.py", line 35, in <module>
    kubin.init_extensions()
  File "W:\kubin\src\env.py", line 31, in init_extensions
    self.ext_registry.register(self)
  File "W:\kubin\src\extension\ext_registry.py", line 59, in register
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'W:\\kubin\\extensions/fb-styles/setup.py'

**Comment by seruva19** [comment]
Oh, sorry for that. It's because there was a breaking change of extensions representation in latest commit.
Try to remove 'fb-styles' folder (and other extensions that do not start with 'kd-') from extensions directory.
With the latest update it should be the following 6 folders there:

1. kd-image-browser
2. kd-interrogator
3. kd-mesh-gen
4. kd-prompt-styles
5. kd-segmentation
6. kd-upscaler

**Comment by videoprice** [comment]
working, thanks
