### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Hodd1444** [seruva19/kubin#95]
Installed kubin like in this tutorial: https://www.youtube.com/watch?v=CVPxw4UDGr4

Then wanted to download the models, so I ran a text2img prompt, this error comes up:

```
task queued: text2img
clearing memory
Traceback (most recent call last):
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\kardinsky\kubin\src\ui_blocks\t2i.py", line 106, in generate
    return generate_fn(params)
  File "D:\AI\kardinsky\kubin\src\webui.py", line 33, in <lambda>
    generate_fn=lambda params: kubin.model.t2i(params),
  File "D:\AI\kardinsky\kubin\src\models\model_kd2.py", line 98, in t2i
    params = self.prepare("text2img").seed(params)
  File "D:\AI\kardinsky\kubin\src\models\model_kd2.py", line 32, in prepare
    self.flush()
  File "D:\AI\kardinsky\kubin\src\models\model_kd2.py", line 83, in flush
    with torch.cuda.device("cuda"):
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\cuda\__init__.py", line 316, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
  File "C:\Users\enter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\cuda\__init__.py", line 77, in _exchange_device
    if device < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

What is also very interesting is, that under the "System"-Tab in Settings it says I have 0 VRAM.

Any help is appreciated!

**Comment by seruva19** [comment]
I've never encountered such error before, so I am not sure... Looks like it cannot locate your graphics card.
What GPU do you have? And if it's NVIDIA, what does command "nvidia-smi" outputs?
Also check torch version (like this):
```
python
import torch
torch.__version__
```

**Comment by Superbelko** [comment]
Had same issue with fresh install, `torch.cuda.is_available()` returned false, so I just re-installed torch and it worked.
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 --force-reinstall`

What this means is that basically torch had to be installed first, before pip install requirements, just like in stable diffusion webui.

**Comment by seruva19** [comment]
@Superbelko Thanks!
The very first version of requirements.txt actually contained torch installation line, but then removed it, because I didn't want to force user to use specific torch version. Guess this decision was suboptimal :(

**Comment by Superbelko** [comment]
Better not.
From my experience many ML project asks user to install torch-torchvision-torchaudio manually before running setup.py/requirements as it is 2.5GB download for Nvidia and about 1.8GB for AMD.

Also from my experience, auto111 had it in requirements for few months and it was annoying to use on AMD cards as it was reinstalling CUDA version every time, had to manually remove it from requirements.txt to be able to use it.
